spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/anielskistyl
    username: anielskistyl
    password: anielskistyle
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true