spring:
  datasource:
#    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/as
    username: as
    password: as
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true